--1
SELECT STUDENT_NO 학번, STUDENT_NAME 이름, TO_CHAR(ENTRANCE_DATE, 'YYYY-MM-DD') 입학년도  
FROM TB_STUDENT
WHERE DEPARTMENT_NO = 002
ORDER BY ENTRANCE_DATE ;

--2
SELECT PROFESSOR_NAME, PROFESSOR_SSN 
FROM TB_PROFESSOR 
WHERE LENGTH(PROFESSOR_NAME) <> 3;

--3
SELECT PROFESSOR_NAME, TRUNC(MONTHS_BETWEEN(SYSDATE,TO_DATE(SUBSTR(PROFESSOR_SSN, 1,6)+19000000))/12) 나이
FROM TB_PROFESSOR
WHERE SUBSTR(PROFESSOR_SSN, 8, 1) = 1 
ORDER BY 나이;

--4 
SELECT SUBSTR(PROFESSOR_NAME,2)
FROM TB_PROFESSOR;

--5
SELECT STUDENT_NO, STUDENT_NAME 
FROM TB_STUDENT
WHERE  EXTRACT( YEAR FROM ENTRANCE_DATE  ) - (SUBSTR(STUDENT_SSN, 1, 2)+1900) > 19;

--6
SELECT 
TO_CHAR(TO_DATE(20201225, 'YYYY/MM/DD'), 'DAY')
FROM DUAL;

--7
/* 1.2099년 10월 11일과 2049년 10월 11일을 의미한다. 
 * 2.1999년 10월 11일과 2049년 10월 11일을 의미한다.
 * */

--8
SELECT STUDENT_NO, STUDENT_NAME 
FROM TB_STUDENT 
WHERE SUBSTR(STUDENT_NO,1,1) <> 'A';

--9
SELECT ROUND(AVG(POINT),1) 평점
FROM TB_GRADE
WHERE STUDENT_NO LIKE 'A517178'

--10
SELECT DEPARTMENT_NO ,COUNT(*)  
FROM TB_STUDENT 
GROUP BY DEPARTMENT_NO
ORDER BY DEPARTMENT_NO;

--11
SELECT COUNT(*)  
FROM TB_STUDENT
WHERE COACH_PROFESSOR_NO IS NULL;

--12
SELECT SUBSTR(TERM_NO, 1, 4) 년도, ROUND(AVG(POINT), 1) "년도 별 평점"
FROM TB_GRADE 
WHERE STUDENT_NO LIKE 'A112113'
GROUP BY SUBSTR(TERM_NO, 1, 4)
ORDER BY 년도;

--13
SELECT DEPARTMENT_NO, COUNT(DECODE(ABSENCE_YN, 'Y', 'Y', 'N' , NULL))
FROM TB_STUDENT 
GROUP BY DEPARTMENT_NO 
ORDER BY DEPARTMENT_NO;

--14
SELECT STUDENT_NAME, count(*)
FROM TB_STUDENT 
GROUP BY STUDENT_NAME
HAVING count(*)> 1;

--15
SELECT SUBSTR(TERM_NO, 1, 4) 년도, SUBSTR(TERM_NO, 5, 2) 학기, ROUND(AVG(POINT), 1) 평점
FROM TB_GRADE
WHERE STUDENT_NO LIKE 'A112113'
GROUP BY ROLLUP(SUBSTR(TERM_NO, 1, 4), SUBSTR(TERM_NO, 5, 2))
ORDER BY SUBSTR(TERM_NO, 1, 4), SUBSTR(TERM_NO, 5, 2);

