CREATE TABLE "BOARD" (
	NUM NUMBER PRIMARY KEY,
	TITLE VARCHAR2(50) NOT NULL,
	WRITER VARCHAR2(50) NOT NULL,
	CONTENT VARCHAR2(1000) NOT NULL,
	REGDATE DATE,
	CNT NUMBER DEFAULT 0
);

CREATE SEQUENCE "BOARD_SEQ"
	START WITH 1
	INCREMENT BY 1
	MAXVALUE 999999
	NOCACHE
	NOCYCLE
	NOORDER;
	
INSERT INTO BOARD VALUES ("BOARD_SEQ".nextval, '제목1', '작성자1', '내용1', SYSDATE, 0 );
INSERT INTO BOARD VALUES ("BOARD_SEQ".nextval, '제목2', '작성자2', '내용2', SYSDATE, 0 );
INSERT INTO BOARD VALUES ("BOARD_SEQ".nextval, '제목3', '작성자3', '내용3', SYSDATE, 0 );
INSERT INTO BOARD VALUES ("BOARD_SEQ".nextval, '제목4', '작성자4', '내용4', SYSDATE, 0 );
INSERT INTO BOARD VALUES ("BOARD_SEQ".nextval, '제목5', '작성자5', '내용5', SYSDATE, 0 );

SELECT * FROM BOARD;

UPDATE BOARD SET TITLE = '제목 수정', CONTENT = '내용 수정' WHERE NUM = 1;

DELETE FROM BOARD WHERE NUM  =1;

COMMIT;

INSERT INTO BOARD VALUES ()



